"""
src/agents/state.py
────────────────────
Shared state schema for the LangGraph multi-agent graph.

Every node in the graph reads from and writes to this single TypedDict.
LangGraph merges partial updates returned by each node — you only need
to return the keys you changed.

Flow:
  User question
      → SupervisorAgent  writes: intent, agent_route, plan
      → RetrieverAgent   writes: rag_answer, rag_sources, rag_chunks
      → SQLAgent         writes: sql_query, sql_result, sql_answer
      → SynthesizerAgent writes: final_answer, final_sources
      → END

Memory:
  chat_history accumulates (role, content) pairs across turns.
  All agents read it so they have conversational context.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict


class AgentState(TypedDict, total=False):
    """
    Shared mutable state passed between all LangGraph nodes.

    Fields added per phase:
      question        — raw user input (set at graph entry)
      persona         — active persona (analyst/executive/engineer/hr)
      chat_history    — list of {"role": ..., "content": ...} dicts (memory)

      intent          — classified intent: "rag" | "sql" | "both" | "chitchat"
      agent_route     — list of agents to invoke: e.g. ["retriever", "sql"]
      plan            — supervisor's free-text reasoning (for debugging)

      rag_answer      — answer from RetrieverAgent
      rag_sources     — list of source citation strings
      rag_chunks      — number of chunks retrieved

      sql_query       — the SQL generated by SQLAgent
      sql_result      — raw DataFrame as dict (JSON-serialisable)
      sql_answer      — natural-language interpretation of the SQL result

      final_answer    — synthesized answer (from SynthesizerAgent)
      final_sources   — merged, deduplicated source list
      error           — error message if any node fails (allows graceful degradation)
    """

    # ── Entry ──────────────────────────────────────────────────────────────────
    question:      str
    persona:       str
    chat_history:  List[Dict[str, str]]

    # ── Supervisor ─────────────────────────────────────────────────────────────
    intent:        str                   # "rag" | "sql" | "both" | "chitchat"
    agent_route:   List[str]             # ["retriever"] | ["sql"] | ["retriever","sql"]
    plan:          str                   # supervisor's reasoning trace

    # ── Retriever Agent ────────────────────────────────────────────────────────
    rag_answer:    str
    rag_sources:   List[str]
    rag_chunks:    int

    # ── SQL Agent ──────────────────────────────────────────────────────────────
    sql_query:     str
    sql_result:    Optional[Dict[str, Any]]   # DataFrame.to_dict("records")
    sql_answer:    str

    # ── Synthesizer ────────────────────────────────────────────────────────────
    final_answer:  str
    final_sources: List[str]

    # ── Error handling ─────────────────────────────────────────────────────────
    error:         Optional[str]